spring:
  cloud:
    stream:
      binders:
        rabbitmq-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${rabbitmq.host}
                port: ${rabbitmq.port}
                username: ${rabbitmq.username}
                password: ${rabbitmq.password}
      default-binder: rabbitmq-binder
      rabbit:
        bindings:
          # Outgoing RabbitMQ bindings
          ## File Upload Session Completed Event
          fileUploadSessionCompletedEvent-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange
              routingKeyExpression: "'storage.file:upload-session.completed'"
          fileUploadSessionCompletedEventError-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange.error
              routingKeyExpression: "'storage.file:upload-session.completed'"
              queueNameGroupOnly: true
          ## File Upload Session Closed Event
          fileUploadSessionClosedEvent-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange
              routingKeyExpression: "'storage.file:upload-session.closed'"
          fileUploadSessionClosedEventError-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange.error
              routingKeyExpression: "'storage.file:upload-session.closed'"
              queueNameGroupOnly: true
          ## File Upload Session Aborted Event
          fileUploadSessionAbortedEvent-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange
              routingKeyExpression: "'storage.file:upload-session.aborted'"
          fileUploadSessionAbortedEventError-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange.error
              routingKeyExpression: "'storage.file:upload-session.aborted'"
              queueNameGroupOnly: true
          # ---------------------------------------
          # Incoming RabbitMQ bindings
          ## File Upload Session Completed Event
          fileUploadSessionCompletedEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: storage.file:upload-session.completed
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.file:upload-session.completed.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: storage.file:upload-session.completed
              republishToDlq: false
              dlqTtl: 5000
          ## File Upload Session Closed Event
          fileUploadSessionClosedEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: storage.file:upload-session.closed
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.file:upload-session.closed.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: storage.file:upload-session.closed
              republishToDlq: false
              dlqTtl: 5000
          ## File Upload Session Aborted Event
          fileUploadSessionAbortedEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: storage.file:upload-session.aborted
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.file:upload-session.aborted.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: storage.file:upload-session.aborted
              republishToDlq: false
              dlqTtl: 5000

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:rabbitmq}
  password: ${RABBITMQ_PASSWORD:rabbitmq}




