spring:
  cloud:
    stream:
      binders:
        rabbitmq-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${rabbitmq.host}
                port: ${rabbitmq.port}
                username: ${rabbitmq.username}
                password: ${rabbitmq.password}
      default-binder: rabbitmq-binder
      rabbit:
        bindings:
          # Outgoing RabbitMQ bindings
          ## File Upload Session Canceled Event
          fileUploadSessionCanceledEvent-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange
              routingKeyExpression: "'storage.file:upload-session.canceled'"
          fileUploadSessionCanceledEventError-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange.error
              routingKeyExpression: "'storage.file:upload-session.canceled'"
              queueNameGroupOnly: true
          ## File Upload Session Marked For Deletion Event
          fileUploadSessionMarkedForDeletionEvent-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange
              routingKeyExpression: "'storage.file:upload-session.marked-for-deletion'"
          fileUploadSessionMarkedForDeletionEventError-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange.error
              routingKeyExpression: "'storage.file:upload-session.marked-for-deletion'"
              queueNameGroupOnly: true
          ## File Upload Session Processing Initiated Event
          fileUploadSessionProcessingInitiatedEvent-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange
              routingKeyExpression: "'storage.file:upload-session.processing-initiated'"
          fileUploadSessionProcessingInitiatedEventError-out-0:
            producer:
              exchangeType: topic
              destination: storage.exchange.error
              routingKeyExpression: "'storage.file:upload-session.processing-initiated'"
              queueNameGroupOnly: true
          # Incoming RabbitMQ bindings
          ## File Upload Session Canceled Event
          fileUploadSessionCanceledEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: storage.file:upload-session.canceled
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.file:upload-session.canceled.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: storage.file:upload-session.canceled
              republishToDlq: false
              dlqTtl: 5000
          ## File Upload Session Marked For Deletion Event
          fileUploadSessionMarkedForDeletionEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: storage.file:upload-session.marked-for-deletion
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.file:upload-session.marked-for-deletion.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: storage.file:upload-session.marked-for-deletion
              republishToDlq: false
              dlqTtl: 5000
          ## File Upload Session Processing Initiated Event
          fileUploadSessionProcessingInitiatedEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: storage.file:upload-session.processing-initiated
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.file:upload-session.processing-initiated.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: storage.file:upload-session.processing-initiated
              republishToDlq: false
              dlqTtl: 5000

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:rabbitmq}
  password: ${RABBITMQ_PASSWORD:rabbitmq}




