spring:
  cloud:
    function:
      definition: fileUploadSessionCanceledConsumer;fileUploadSessionMarkedForDeletionConsumer;fileUploadSessionProcessingInitiatedConsumer
    stream:
      function:
        bindings:
          fileUploadSessionCanceledConsumer-in-0: fileUploadSessionCanceledEvent-in-0
          fileUploadSessionMarkedForDeletionConsumer-in-0: fileUploadSessionMarkedForDeletionEvent-in-0
          fileUploadSessionProcessingInitiatedConsumer-in-0: fileUploadSessionProcessingInitiatedEvent-in-0
      default:
        content-type: application/json
      bindings:
        # Outgoing bindings
        ## File Upload Session Canceled Event
        fileUploadSessionCanceledEvent-out-0:
          destination: storage.exchange
        fileUploadSessionCanceledEventError-out-0:
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.file:upload-session.canceled.queue.error
        ## File Upload Session Marked For Deletion Event
        fileUploadSessionMarkedForDeletionEvent-out-0:
          destination: storage.exchange
        fileUploadSessionMarkedForDeletionEventError-out-0:
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.file:upload-session.marked-for-deletion.queue.error
        ## File Upload Session Processing Initiated Event
        fileUploadSessionProcessingInitiatedEvent-out-0:
          destination: storage.exchange
        fileUploadSessionProcessingInitiatedEventError-out-0:
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.file:upload-session.processing-initiated.queue.error
        # Incoming bindings
        ## File Upload Session Canceled Event
        fileUploadSessionCanceledEvent-in-0:
          destination: storage.exchange
          group: storage.file:upload-session.canceled.queue
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.consumer.file-upload-session-canceled-event.concurrency}
        ## File Upload Session Marked For Deletion Event
        fileUploadSessionMarkedForDeletionEvent-in-0:
          destination: storage.exchange
          group: storage.file:upload-session.marked-for-deletion.queue
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.consumer.file-upload-session-marked-for-deletion-event.concurrency}
        ## File Upload Session Processing Initiated Event
        fileUploadSessionProcessingInitiatedEvent-in-0:
          destination: storage.exchange
          group: storage.file:upload-session.processing-initiated.queue
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.consumer.file-upload-session-processing-initiated-event.concurrency}


