spring:
  cloud:
    function:
      definition: fileUploadSessionCompletedConsumer;fileUploadSessionAbortedConsumer
    stream:
      function:
        bindings:
          fileUploadSessionCompletedConsumer-in-0: fileUploadSessionCompletedEvent-in-0
          fileUploadSessionAbortedConsumer-in-0: fileUploadSessionAbortedEvent-in-0
      default:
        content-type: application/json
      bindings:
        # Outgoing bindings
        ## File Upload Session Completed Event
        fileUploadSessionCompletedEvent-out-0:
          destination: storage.exchange
        fileUploadSessionCompletedEventError-out-0:
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.file:upload-session.completed.queue.error
        ## File Upload Session Aborted Event
        fileUploadSessionAbortedEvent-out-0:
          destination: storage.exchange
        fileUploadSessionAbortedEventError-out-0:
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.file:upload-session.aborted.queue.error
        # ---------------------------------------
        # Incoming bindings
        ## File Upload Session Completed Event
        fileUploadSessionCompletedEvent-in-0:
          destination: storage.exchange
          group: storage.file:upload-session.completed.queue
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.consumer.file-upload-session-completed-event.concurrency}
        ## File Upload Session Aborted Event
        fileUploadSessionAbortedEvent-in-0:
          destination: storage.exchange
          group: storage.file:upload-session.aborted.queue
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.consumer.file-upload-session-aborted-event.concurrency}
        # ---------------------------------------
